### ISSUE TITLE
it is useful to gzip consensus.db

### ISSUE THREAD

**Issue by legolegs** [S-anasol/consensus.siahub.info#3]
A gzipped consensus.db takes 50% less space and doubles the effective download speed. It is very easy to do, just replace `cp real/consensus.db web/consensus.db` with `gzip < real/consensus.db > web/consensus.db.gz`

Here is more complicated cronfile which computes necessary checksums on the fly doing only one pass:
```
SHELL=/bin/bash
0 */24 * * *     root cd /home/consensus.siahub/ && tee >(sha256sum | sed 's/-/consensus.db/' > consensus.db.sha256sum ) < /home/sia/host/consensus/consensus.db | gzip | tee >(sha256sum | sed 's/-/consensus.db.gz/' >consensus.db.gz.sha256sum ) >consensus.db.gz
```

**Comment by sanasol** [comment]
I'll try add it, nice idea.

**Comment by sanasol** [comment]
Added gzipping

Really 2x smaller 👌
